# Generated by Django 5.0 on 2024-01-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_signin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_email',
        ),
        migrations.DeleteModel(
            name='SignIn',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
