# Generated by Django 5.0 on 2024-01-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter1whoareyou',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
