# Generated by Django 5.0 on 2024-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parameterimgmyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterimgmyphoto',
            name='image',
            field=models.ImageField(upload_to='uploaded'),
        ),
    ]
