# Generated by Django 5.0 on 2024-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_parameter2whatdoyoudo_parameter3environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter3environment',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter3environment',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter3environment',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter4habits',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter4habits',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter4habits',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter5freetime',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter5freetime',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter5freetime',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter6looklike',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter6looklike',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter6looklike',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter7behavior',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter7behavior',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter7behavior',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter8thoughtsdirection',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter8thoughtsdirection',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter8thoughtsdirection',
            name='what_why_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameterimgmyphoto',
            name='date_time',
            field=models.DateTimeField(default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameterimgmyphoto',
            name='date_time_pict',
            field=models.DateTimeField(blank=True, default='2024-01-07 20:19:11'),
            preserve_default=False,
        ),
    ]
