# Generated by Django 5.0 on 2024-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_parameter2whatdoyoudo_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='text1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='text3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='text4',
            field=models.TextField(blank=True),
        ),
    ]
