# Generated by Django 5.0 on 2024-01-20 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_parameter3environment_text1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameter6LookLike',
            new_name='Parameter6Appearance',
        ),
        migrations.RenameModel(
            old_name='Parameter8ThoughtsDirection',
            new_name='Parameter8Mind',
        ),
        migrations.AlterModelOptions(
            name='parameter6appearance',
            options={'verbose_name_plural': 'Parameter6Appearance'},
        ),
        migrations.AlterModelOptions(
            name='parameter8mind',
            options={'verbose_name_plural': 'Parameter8Mind'},
        ),
    ]
