# Generated by Django 5.0 on 2024-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_parameter6looklike_parameter6appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter1whoareyou',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter2whatdoyoudo',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter3environment',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter4habits',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter5freetime',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter6appearance',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter7behavior',
            name='text0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter8mind',
            name='text0',
            field=models.TextField(blank=True),
        ),
    ]
