# Generated by Django 5.0 on 2024-01-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_parameterimgmyphoto_date_time_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterimgmyphoto',
            name='date_time_pict',
            field=models.DateTimeField(default='2024-12-31 12:20:54'),
        ),
    ]
