# Generated by Django 5.0 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_parameterimgmyphoto_date_time_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterimgmyphoto',
            name='date_time',
            field=models.DateTimeField(default='02/20/2005 17:25'),
        ),
    ]
